### ISSUE TITLE
Security issue: Any user on the system can look on ps -f and catch password

### ISSUE THREAD

**Issue by gitdev-bash** [nisay759/sudo-backdoor#1]
Any user on the system can look on ps -fu $user and catch password if he is looking for it

**Comment by nisay759** [comment]
Sorry for the late reply, but won't fix. This is not a security product, its main goal is to extract a password, so finding the said password is kind of the purpose. Feel free to adapt the extraction method to your needs by obfuscating the password how you see fit.
